name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Backend Docker image
      run: docker build . --file backend/Dockerfile --tag jattstats-backend:$(date +%s)
    - uses: actions/checkout@v2
    - name: Build the Frontend Docker image
      run: docker build . --file frontend/jatt-stats/Dockerfile --tag jattstats-frontend:$(date +%s)
